### ISSUE TITLE
Have we pondered the possibility of making a lightweight "web-installer"?

### ISSUE THREAD

**Issue by cheatfreak47** [Carlmundo/BetterSADX#3]
A lot of the mods BetterSADX is made of are online, in theory we could make a web-installer for a large chunk of the stuff we include, especially Dreamcast Conversion which is hosted on PieKeyAr's Server.

This is obviously a future development concept, but it would be kind of neat

**Comment by Carlmundo** [comment]
I have thought about it and here's why I would be against it.

Mods that are hosted on an individual's server are a potential problem. If they lose interest or motivation (which they likely will at some point) and they don't renew their server then our installer breaks and people are left waiting. And if WE lose motivation then BetterSADX will no longer continue to function,

In the interest of keeping BetterSADX alive forever/as long as possible I think we should keep the content local to the install.
