### ISSUE TITLE
Possible Issue breaking various story mode flags

### ISSUE THREAD

**Issue by cheatfreak47** [Carlmundo/BetterSADX#5]
A couple people have reported in the bettersadx comments an issue involving their game breaking somewhere along the way with the Dreamcast Conversion installed, I think it's one of the DC Mods faults but I have no idea what- but I'll do a playthrough again anyway just to confirm this issue not present after 4.1.1 releases.

**Comment by thayssa-cyber** [comment]
> A couple people have reported in the bettersadx comments an issue involving their game breaking somewhere along the way with the Dreamcast Conversion installed, I think it's one of the DC Mods faults but I have no idea what- but I'll do a playthrough again anyway just to confirm this issue not present after 4.1.1 releases.
