### ISSUE TITLE
Change project tagline

### ISSUE THREAD

**Issue by cheatfreak47** [Carlmundo/BetterSADX#6]
I've decided that it'd be best if we ditch the whole "definitive" bit because I kind of find that line a little cringey.

Instead we should go with: "A patcher and mod-pack for Sonic Adventure DX."
Which is a more accurate description anyway.

**Comment by Carlmundo** [comment]
I don't think it's so bad. Let's ask some people :)

**Comment by cheatfreak47** [comment]
Even if BetterSADX is the most defined version of the game, I find the notion of calling one's own project the best a bit arrogant, and that's not really the way I like the project to come off, especially considering a large majority of the content isn't really our work.

On the guide I changed it to:

"A patcher and mod-pack for Sonic Adventure DX.

BetterSADX is an easy to install / automated patch that transforms the Steam port of Sonic Adventure DX into an enhanced version of the original 2004 port with many more features that have been added by members of the community over the last several years."
